#!/usr/bin/env python

from os import path, chdir
from subprocess import call

def build():
    root = path.abspath(path.dirname((path.dirname(__file__))))

    chdir(root)
    call(['python', 'setup.py', 'sdist', 'bdist_wheel'])

if __name__ == '__main__':
    build()
