#!/usr/bin/env python

from os import path
from os import remove as rm
from shutil import rmtree as rmdir

root = path.abspath(path.dirname((path.dirname(__file__))))

dirs = ['dist', 'build', 'pwned/__pycache__']

for dir in dirs:
    fpath = path.join(root, dir)

    if path.exists(path.join(root, dir)):
        rmdir(fpath)
        print("Deleted %s" % fpath)
