#!/usr/bin/env python

from os import path, chdir
from subprocess import call

from build import build
from pwned import __version__

if __name__ == '__main__':
    root = path.abspath(path.dirname((path.dirname(__file__))))
    build()

    call(['pip', 'install', path.join(root, 'dist/pwned-{}-py3-none-any.whl'
                                      .format(__version__))])
